### ISSUE TITLE
Missing checksums and signatures for images

### ISSUE THREAD

**Issue by xypron** [starfive-tech/Fedora_on_StarFive#14]
It would be great if checksums and signatures would be provided for images.

**Comment by pdp7** [comment]
@xypron good idea, I'll update the README with that

**Comment by pdp7** [comment]
@tekkamanninja is there a gpg key that you would like to use to sign with?  otherwise I could use mine.

**Comment by MichaelZhuxx** [comment]
from 0822 image, it has a pgp signature:
https://fedora.starfivetech.com/pub/downloads/BeagleV-release/Fedora-riscv64-developer-xfce-with-esp-Rawhide-20210822.n.0-sda.raw.zst.asc
