### ISSUE TITLE
What is the U74 core frequency?

### ISSUE THREAD

**Issue by pdp7** [starfive-tech/Fedora_on_StarFive#17]
Several beta developers have asked what frequency the U74 cores are running at.

**Comment by pdp7** [comment]
Initial response is 1.5GHz.

@MichaelZhuxx would you be able to point to where this is configured? (such as in secondBoot, uboot or kernel)

**Comment by MichaelZhuxx** [comment]
@pdp7 the cpu core frequency is 1GHz which is configred in secondBoot(https://github.com/starfive-tech/beagle_secondBoot/blob/44193cbfb0905c5d174798fad4e5ffe357e5441e/common/clkgen_ctrl_macro.h#L709:9)

**Comment by pdp7** [comment]
@MichaelZhuxx thank you for the clarification

fyi @brucehoult @davidlt

**Comment by brucehoult** [comment]
Can it be changed dynamically?

On the U54 (at least in the HiFive Unleashed) there is a pseudo file /sys/devices/platform/soc/10000000.prci/rate which you can read or write a new value to and *boom*.  Or, hopefully, not boom.

Even at the default 1.0 GHz I'm seeing performance getting throttled if both cores are loaded so maybe it's not worth trying to adjust it.

Advertising does say it's a 1.5 GHz machine. I've been running my HiFIve Unleashed (which also uses a MPW chip) at 1.45 GHz for three years, stably at sometimes constant full load on all cores.

**Comment by pdp7** [comment]
I have gotten clarification from StarFive that the JH7100 is fixed at 1GHz and can not be changed.
