### ISSUE TITLE
'fedora-vic7100': Cannot download repomd.xml

### ISSUE THREAD

**Issue by xypron** [starfive-tech/Fedora_on_StarFive#18]
Yum on the Fedora image fails to use a repository http://openkoji.iscas.ac.cn/riscv-extras/vic7100/repodata/repomd.xml.

```
$ sudo yum install at
Feodra VIC7100 support                                                                        127  B/s | 196  B     00:01    
Errors during downloading metadata for repository 'fedora-vic7100':
  - Status code: 404 for http://openkoji.iscas.ac.cn/riscv-extras/vic7100/repodata/repomd.xml (IP: 124.16.138.121)
Error: Failed to download metadata for repo 'fedora-vic7100': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: fedora-vic7100
```

* Is that repository required?
* Where did it move?

**Comment by pdp7** [comment]
@tekkamanninja I think this is the Chinese Academy of Science?

**Comment by gavan1** [comment]
@xypron but it won't stop you installing packages. Make sure you start with

`sudo dnf upgrade --best`

a tip is to try your luck with as it might already be installed after the dnf upgrade.

`sudo dnf info <package>`

**Comment by xypron** [comment]
If the repo is not needed, it should be removed. For security reasons it is better to have as few repos as possible.

**Comment by pdp7** [comment]
@xypron thank you, I will sync up with Wei Fu (@tekkamanninja) about removing it.

**Comment by tekkamanninja** [comment]
please check here 
https://fedora.starfivetech.com:8443/kojifiles/repos/f33-build/latest/groups/comps.xml

**Comment by pdp7** [comment]
@tekkamanninja does that fix this problem?
