### ISSUE TITLE
update submodules with new fedora branches

### ISSUE THREAD

**Issue by pdp7** [starfive-tech/Fedora_on_StarFive#19]
@tekkamanninja Could you update the submodules to use the new Fedora branches?
* https://github.com/starfive-tech/opensbi/tree/StarFive_VIC_7100
* https://github.com/starfive-tech/linux/tree/fedora-vic-7100_5.10.6
* https://github.com/starfive-tech/u-boot/tree/Fedora_VIC_7100_2021.04

**Comment by pdp7** [comment]
@tekkamanninja maybe this can be done now that there are new branches?

**Comment by MichaelZhuxx** [comment]
update submodules to the below branch:
https://github.com/starfive-tech/u-boot/tree/Fedora_JH7100_upstream
https://github.com/starfive-tech/linux/tree/beaglev
https://github.com/starfive-tech/opensbi/tree/master
