### ISSUE TITLE
[eth0] Link is offline after system boots up

### ISSUE THREAD

**Issue by MichaelZhuxx** [starfive-tech/Fedora_on_StarFive#2]
Based on fedora image: Fedora-riscv64-vic7100-dev-raw-image-Rawhide-20210419121453.n.0-sda.raw

After the fedora system starts, eth0 link is offline. 
then replug the network cable, eth0 link is online, and the following information on the terminal:

`[root@fedora-starfive ~]# stmmaceth 10020000.gmac eth0: Link is Up - 1Gbps/Full - flow control rx/tx`

after that, pull out the cable, show the following log:

`[root@fedora-starfive ~]# stmmaceth 10020000.gmac eth0: Link is Down`

then plug the cable back in, eth0 link is still offline.

So there is a cycle, where the network intermittently disconnects and connects as the network cable is plugged/replugged

**Comment by aurel32** [comment]
Another workaround that does not need a physical access to the board is to run `mii-tool -R eth0`

**Comment by pdp7** [comment]
@aurel32 thanks!

@lakshanthad could you please try `mii-tool -R eth0` and add it to the Getting Started?

**Comment by lakshanthad** [comment]
For sure. I will add accordingly

**Comment by aurel32** [comment]
On a debian installation, this could be added to /etc/network/interfaces the following way:

```
auto eth0
iface eth0 inet static
        address xx.xx.xx.xx/xx
        gateway xx.xx.xx.xx
        post-up mii-tool -R $IFACE 
```

**Comment by pdp7** [comment]
FYI - from @Esmil on slack:

> As for the network it seems to work fine for me once it has seen the link. I use this `/etc/systemd/system/mii-reset.service` to make sure it detects the link at boot:

mii-reset.service:
```
[Unit]
Description=Reset MII to detect link
StartLimitIntervalSec=5
StartLimitBurst=5

[Service]
Type=oneshot
ExecStart=/usr/sbin/mii-tool -R eth0
Restart=on-failure
RestartSec=500ms

[Install]
WantedBy=sys-devices-platform-soc-10020000.gmac-net-eth0.device
```

**Comment by geertu** [comment]
Does your kernel have CONFIG_MICREL_PHY=y?

I had a similar issue with booting from nfsroot: the kernel waits for the network, until I replugged the Ethernet cable.
Enabling CONFIG_MICREL_PHY for the Micrel KSZ9031 PHY fixed that.

starfive_vic7100_evb_sd_net_defconfig and starfive_vic7100_evb_sd_net_usb_defconfig have support for Marvell PHYs enabled (why?), but not support for Micrel PHYs:
CONFIG_MARVELL_PHY=y
# CONFIG_MICREL_PHY is not set

**Comment by esmil** [comment]
@geertu Awesome! Can confirm. This makes my `mii-reset.service` above completely unnecessary.

**Comment by pdp7** [comment]
> CONFIG_MICREL_PHY
@tekkamanninja is this enabled in the fedora defconfig?

**Comment by aurel32** [comment]
> > CONFIG_MICREL_PHY
> > @tekkamanninja is this enabled in the fedora defconfig?

I confirm that solution work. It is enabled in the fedora config, but doesn't seem to get loaded. I wonder if it's due to the fact that the stmmac driver is builtin while the PHY driver is a module.

**Comment by geertu** [comment]
> > > CONFIG_MICREL_PHY
> > > @tekkamanninja is this enabled in the fedora defconfig?
> 
> I confirm that solution work. It is enabled in the fedora config, but doesn't seem to get loaded. I wonder if it's due to the fact that the stmmac driver is builtin while the PHY driver is a module.

Commit 21e194425abd65b5 ("net: phy: fix issue with loading PHY driver w/o initramfs") suggests modular PHY drivers could work.  But that will fail if the stmmac driver is initialized before the module is available.

**Comment by aurel32** [comment]
With the PHY as a module, I have:
`stmmaceth 10020000.gmac eth0: PHY [stmmac-0:00] driver [Generic PHY] (irq=POLL)`
With the PHY builtin:
`stmmaceth 10020000.gmac eth0: PHY [stmmac-0:00] driver [Micrel KSZ9031 Gigabit PHY] (irq=POLL)`

**Comment by xypron** [comment]
module micrel is not contained in the initial RAM disk.

**Comment by pdp7** [comment]
> With the PHY as a module, I have:
> `stmmaceth 10020000.gmac eth0: PHY [stmmac-0:00] driver [Generic PHY] (irq=POLL)`
> With the PHY builtin:
> `stmmaceth 10020000.gmac eth0: PHY [stmmac-0:00] driver [Micrel KSZ9031 Gigabit PHY] (irq=POLL)`

Is ethernet working when phy driver is builtin?

@tekkamanninja found that Ethernet did not work when having both stmmac and micrel phy drivers both builtin.

**Comment by aurel32** [comment]
Yep for me with the PHY builtin, the Ethernet works fine, no need to unplug the cable or use mii-tool. Note however that I am using the 5.12 branch from Esmil.

**Comment by xypron** [comment]
It should be sufficient toto add the micrel module to the dracut configuration.

**Comment by MichaelZhuxx** [comment]
this issue is fixed by latest Fedora image https://files.beagle.cc/file/beagleboard-public-2021/images/Fedora-riscv64-vic7100-xfce-dev-Rawhide-20210516233526.n.0-sda.raw.zst
