### ISSUE TITLE
Excessive kernel logging slowing down some USB Mass Storage devices

### ISSUE THREAD

**Issue by hamsternz** [starfive-tech/Fedora_on_StarFive#20]
When using some USB drives (in this case an Transcend External USB 3.0 SSD) performance is very suboptimal (< 10 MBs), even when connected through a USB 2.0 hub.

    [root@fedora-starfive ~]# dd if=/dev/sda bs=16k count=16384 of=/dev/null
    16384+0 records in
    16384+0 records out
    268435456 bytes (268 MB, 256 MiB) copied, 29.0586 s, 9.2 MB/s
    [root@fedora-starfive ~]#

I have traced this to logging of these kernel message:

    ...
    [ 1017.415867] L2CACHE: flush64 out of range: 2080200000(80000), skip flush
    [ 1017.433512] L2CACHE: flush64 out of range: 2080200000(80000), skip flush
    [ 1017.451112] L2CACHE: flush64 out of range: 2080200000(80000), skip flush.
    ...

After the disabling kernel logging with 

    sysctl -w kernel.printk="2 4 1 7"

performance returns to expected levels, regardless of "SuperSpeed USB" or "highspeed USB" connection

    [root@fedora-starfive kernel]# dd if=/dev/sda of=/dev/null bs=16k count=16384
    16384+0 records in
    16384+0 records out
    268435456 bytes (268 MB, 256 MiB) copied, 5.32661 s, 50.4 MB/s

This may just be a manifestation of the L2 cache flushing, but it seems odd how USB flash disks are immune to this, but USB SSDs are not.

**Comment by pdp7** [comment]
@tekkamanninja we talked today in the starfive meeting about whether this should be logged or not.  It seems like it might be causing a performance problem.

**Comment by robertlipe** [comment]
It's not a fix, but you may get relief from pain killer.

Consider replacing that printk with printk_ratelimited() or printk_once().  They do exactly what you think they should.

In any high-volume path (per packet, per disk I/o, etc.) these are good to remember.

**Comment by pdp7** [comment]
@tekkamanninja has fixed in https://github.com/starfive-tech/linux/commit/cc87a4619c8d4532e3858aa30fd16b50c2d0a125

Please help test this so it can included in the next Fedora image

**Comment by rwmjones** [comment]
@tekkamanninja Wei, is there a new kernel build in koji you'd like us to try?

**Comment by tekkamanninja** [comment]
> @tekkamanninja Wei, is there a new kernel build in koji you'd like us to try?

yes, we did it:   https://fedora.starfivetech.com:8443/koji/buildinfo?buildID=18

**Comment by tekkamanninja** [comment]
> > @tekkamanninja Wei, is there a new kernel build in koji you'd like us to try?
> 
> yes, we did it: https://fedora.starfivetech.com:8443/koji/buildinfo?buildID=18

please note: we are preparing the  443 an 80 port for koji now, but we need a month to register the website to the gov. so please download the package by fixing the url(adding :8443) like:

https://fedora.starfivetech.com/kojifiles/packages/kernel-vic7100/5.10.6/210.0.riscv64.fc33/riscv64/kernel-vic7100-5.10.6-210.0.riscv64.fc33.riscv64.rpm

**Comment by rwmjones** [comment]
This worked for me:

```
$ wget --no-check-certificate -r -np -e robots=off https://fedora.starfivetech.com:8443/kojifiles/packages/kernel-vic7100/5.10.6/210.0.riscv64.fc33/riscv64/
```

**Comment by rwmjones** [comment]
Upgraded to the -210 kernel and I do not see any L2CACHE messages when reading or writing to a USB key.

It is still pretty slow though, but I guess that's hardware-related.

```
$ sudo dd if=/dev/zero of=/dev/sda1 count=1024 bs=1M
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 305.167 s, 3.5 MB/s

$ sudo dd if=/dev/sda1 of=/dev/null count=1024 bs=1M
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 57.3213 s, 18.7 MB/s
```

**Comment by pdp7** [comment]
> Upgraded to the -210 kernel and I do not see any L2CACHE messages when reading or writing to a USB key.
> 
> It is still pretty slow though, but I guess that's hardware-related.
> 
> ```
> $ sudo dd if=/dev/zero of=/dev/sda1 count=1024 bs=1M
> 1024+0 records in
> 1024+0 records out
> 1073741824 bytes (1.1 GB, 1.0 GiB) copied, 305.167 s, 3.5 MB/s
> 
> $ sudo dd if=/dev/sda1 of=/dev/null count=1024 bs=1M
> 1024+0 records in
> 1024+0 records out
> 1073741824 bytes (1.1 GB, 1.0 GiB) copied, 57.3213 s, 18.7 MB/s
> ```

@MichaelZhuxx @tekkamanninja you saw 22MB/s with Linux 4.19 correct?

**Comment by pdp7** [comment]
Closing now that @tekkamanninja has put the fix into the Fedora kernel https://github.com/starfive-tech/linux/commit/cc87a4619c8d4532e3858aa30fd16b50c2d0a125
