### ISSUE TITLE
Known good secondBoot/ddrinit/uboot images  for recoevery?

### ISSUE THREAD

**Issue by pdp7** [starfive-tech/Fedora_on_StarFive#21]
@tekkamanninja I have been asked by @lbmeng if we have known good secondBoot/ddrinit/uboot images in case he needs to do recovery while working on bootloader?

**Comment by RobertCNelson** [comment]
I second this! ;)

**Comment by pdp7** [comment]
@tekkamanninja if you can point me at the best secondboot, ddirnit and uboot builds, then @MichaelZhuxx or I could put them in a releases under this repo

**Comment by MichaelZhuxx** [comment]
Please use the below released ddrinit and secondboot, thanks
https://github.com/starfive-tech/beagle_ddrlnit/releases/tag/ddrinit-2133-210302
https://github.com/starfive-tech/beagle_secondBoot/releases/tag/bootloader-210209_BeagleV_Starlight

**Comment by RobertCNelson** [comment]
Thanks so much for including the binary releases in those repo's.. @MichaelZhuxx

**Comment by lbmeng** [comment]
Great, this makes people comforatble to reflash the board :)
Thanks @MichaelZhuxx and @pdp7 !

**Comment by pdp7** [comment]
@lakshanthad could the Getting Started guide link to these releases from @MichaelZhuxx?
https://github.com/starfive-tech/beagle_ddrlnit/releases/tag/ddrinit-2133-210302
https://github.com/starfive-tech/beagle_secondBoot/releases/tag/bootloader-210209_BeagleV_Starlight

**Comment by lakshanthad** [comment]
Yes I will add them @pdp7

**Comment by lakshanthad** [comment]
Shall I close this issue? @pdp7 . The wiki has been updated.

**Comment by pdp7** [comment]
Yes, closing now, thank you
