### ISSUE TITLE
Use Xorg with HDMI?

### ISSUE THREAD

**Issue by pdp7** [starfive-tech/Fedora_on_StarFive#22]
Several questions from Slack and Forum:
@tekkamanninja 
Is it possible to use Xwindows with the current HDMI output?

**Comment by pdp7** [comment]
@tommythorn provided some logs:
```
X.Org X Server 1.20.11
X Protocol Version 11, Revision 0
Build Operating System:  5.5.0-0.rc5.git0.1.1.riscv64.fc32.riscv64
Current Operating System: Linux fedora-starfive 5.10.6+ #26 SMP Tue Apr 20 03:32:34 CST 2021 riscv64
Kernel command line: ro root=UUID=29f097dc-eba8-4043-a650-cfd06eef5461 rhgb console=tty0 console=ttyS0,115200 earlycon=sbi rootwait stmmaceth=>
Build Date: 14 April 2021  12:00:00AM
Build ID: xorg-x11-server 1.20.11-1.fc33
Current version of pixman: 0.40.0
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Tue Apr 27 09:05:24 2021
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Internal error:   Could not resolve keysym XF86FullScreen
Errors from xkbcomp are not fatal to the X server
(II) Server terminated successfully (0). Closing log file.
And this in /var/log/Xorg.0.log
[  8204.306]
X.Org X Server 1.20.11
X Protocol Version 11, Revision 0
[  8204.307] Build Operating System:  5.5.0-0.rc5.git0.1.1.riscv64.fc32.riscv64
[  8204.307] Current Operating System: Linux fedora-starfive 5.10.6+ #26 SMP Tue Apr 20 03:32:34 CST 2021 riscv64
[  8204.307] Kernel command line: ro root=UUID=29f097dc-eba8-4043-a650-cfd06eef5461 rhgb console=tty0 console=ttyS0,115200 earlycon=sbi rootwa>
[  8204.308] Build Date: 14 April 2021  12:00:00AM
[  8204.308] Build ID: xorg-x11-server 1.20.11-1.fc33
[  8204.309] Current version of pixman: 0.40.0
[  8204.309]    Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
[  8204.309] Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational
...
[  8207.293] (II) event2  - PixArt USB Optical Mouse: is tagged by udev as: Mouse
[  8207.295] (II) event2  - PixArt USB Optical Mouse: device set to 1000 DPI
[  8207.296] (II) event2  - PixArt USB Optical Mouse: device is a pointer
[  8207.314] (II) config/udev: Adding input device PixArt USB Optical Mouse (/dev/input/mouse0)
[  8207.315] (II) No input driver specified, ignoring this device.
[  8207.315] (II) This device may have been added with another device file.
[ 10104.649] (II) event0  -   RPI Wired Keyboard 4: device removed
[ 10104.708] (II) event1  -   RPI Wired Keyboard 4: device removed
[ 10104.773] (II) event2  - PixArt USB Optical Mouse: device removed
[ 10104.955] (II) UnloadModule: "libinput"
[ 10104.956] (II) UnloadModule: "libinput"
[ 10104.974] (II) UnloadModule: "libinput"
[ 10105.260] (II) Server terminated successfully (0). Closing log file.
```
Note, no errors in the Xorg.0.log file

**Comment by david-Li-93** [comment]
Hi pdp7
       * Use Xwindows with HDMI？
             ==》  I want to confirm whether the framebuffer architecture supports the XWindows graphical interface ？
             ==》  the framebuffer architecture supports the XWindows graphical
       * Analysis of the log ：
              Internal error:   Could not resolve keysym XF86FullScreen
              Errors from xkbcomp are not fatal to the X server
              ==》This error is a common error on the graphical interface. Please check the website. I hope it will help you。
              ==》    https://bugzilla.redhat.com/show_bug.cgi?id=683950

**Comment by sdanfa** [comment]
> Hi pdp7
> * Use Xwindows with HDMI？
> ==》 I want to confirm whether the framebuffer architecture supports the XWindows graphical interface ？
> ==》 the framebuffer architecture supports the XWindows graphical
> * Analysis of the log ：
> Internal error: Could not resolve keysym XF86FullScreen
> Errors from xkbcomp are not fatal to the X server
> ==》This error is a common error on the graphical interface. Please check the website. I hope it will help you。
> ==》 https://bugzilla.redhat.com/show_bug.cgi?id=683950

Hi David,
I'm trying to use xorg but I'm getting a black screen when launching xorg on the fedora image.

Thanks.

**Comment by pdp7** [comment]
@sdanfa I have not gotten any confirmation from starfive in my weekly meetings that Xwindows is expected to work yet.

@david-Li-93 hello, where did you get this information from?  are you with starfive?

@MichaelZhuxx @tekkamanninja do you have an example of XWindows working on the StarFive JH7100 either with the EVB or the BeagleV beta prototype?

**Comment by david-Li-93** [comment]
Dear sir
        We don't use the GPU on our hardware, so it might be a problem if the graphics desktop relies on the GPU。

**Comment by david-Li-93** [comment]
Dear sir
       * is this a problem with how Xorg is configured in the Fedora image then?
              ==》sir,Xorg is an implementation of X11 that also provides an X Server for Fedora Linux operations。
              ==》We do not support configuration for Xorg
       * Which developers do you mean?
              ==》 I'm sorry. What I mean is that this problem needs to be solved by the R&D engineers themselves

**Comment by pdp7** [comment]
@tekkamanninja tells me that Xorg is working for **remote sessions** in the new Fedora image which should be uploaded soon,  I will update when that has happened.

There is a problem where Xorg will not work over HDMI as the fbdev is not working correctly.

**Comment by MichaelZhuxx** [comment]
We have solved the issue over HDMI and will released in next Fedora image, stay tuned.

**Comment by pdp7** [comment]
@MichaelZhuxx @tekkamanninja  where are the commits that fix this issue?

@kraj wants to pull it into yocto/oe meta-riscv layer https://github.com/riscv/meta-riscv/blob/master/conf/machine/beaglev-starlight-jh7100.conf

**Comment by pdp7** [comment]
@Esmil @geertu @tpetazzoni @kraj 
I learned from @tekkamanninja that this commit fixes the problem with being able to display Xorg on HDMI: 
https://github.com/starfive-tech/linux/commit/e865a75d55e0e4256242e4405b87c394b5885a57

FYI - the [StarFive Koji Fedora sever](https://fedora.starfivetech.com:8443/koji/builds?type=all&userID=&order=-build_id&state=1) is now online.   The latest [Fedora image](https://fedora.starfivetech.com:8443/kojifiles/work/tasks/490/490/Fedora-riscv64-vic7100-xfce-dev-Rawhide-20210512104047.n.0-sda.raw.xz) can be downloaded for testing.  XFCE does work over remote SSH session but it does need the kernel updated with the above fix for XFCE to display on the HDMI.

**Comment by pdp7** [comment]
The new May 16 Fedora image now has XFCE working over HDMI:

**[Fedora-riscv64-vic7100-xfce-dev-Rawhide-20210516233526.n.0-sda.raw.zst](https://files.beagle.cc/file/beagleboard-public-2021/images/Fedora-riscv64-vic7100-xfce-dev-Rawhide-20210516233526.n.0-sda.raw.zst)** [*(sha256sum)*](https://files.beagle.cc/file/beagleboard-public-2021/images/Fedora-riscv64-vic7100-xfce-dev-Rawhide-20210516233526.n.0-sda.raw.zst.sha256sum)

This commit fixes the problem with being able to display Xorg on HDMI:
[starfive-tech/linux@e865a75](https://github.com/starfive-tech/linux/commit/e865a75d55e0e4256242e4405b87c394b5885a57)

![PXL_20210517_050141970 MP](https://user-images.githubusercontent.com/313864/118588729-d9d95680-b753-11eb-9ee9-e5ec30a00c74.jpg)

**Comment by pdp7** [comment]
![Screenshot from 2021-05-17 21-20-55](https://user-images.githubusercontent.com/313864/118589774-ec548f80-b755-11eb-938c-3261150317e3.png)

**Comment by geertu** [comment]
> @esmil @geertu @tpetazzoni @kraj:
> I learned from @tekkamanninja that this commit fixes the problem with being able to display Xorg on HDMI:
> [starfive-tech/linux@e865a75](https://github.com/starfive-tech/linux/commit/e865a75d55e0e4256242e4405b87c394b5885a57)

This commit is present in esmil's v5.13-rc2, and doesn't fix the issue on both my Sony TV and BenQ monitor.

**Comment by HougeLangley** [comment]
Hi, guys, I have problem on my StarFive boot Debian XFCE, so slow.

https://youtu.be/bWVRIPxQ0rc

**Comment by esmil** [comment]
There was recently a user on #debian-riscv talking about Xfce on Debian being slow, but not on the Fedora image. I suggested that it was probably some userspace configuration then. They returned and said Xfce on Ubuntu also worked much better, so maybe you can compare their default configurations / versions.

**Comment by HougeLangley** [comment]
> There was recently a user on #debian-riscv talking about Xfce on Debian being slow, but not on the Fedora image. I suggested that it was probably some userspace configuration then. They returned and said Xfce on Ubuntu also worked much better, so maybe you can compare their default configurations / versions.

Thanks, you means Linux kernel userspace configure?

**Comment by esmil** [comment]
No userspace. He said he was using the same kernel, but Xfce was slow on Debian and fast on Ubuntu.

**Comment by Zeno-sole** [comment]
> > No userspace. They said they were using the same kernel, but Xfce was slow on Debian and fast on Ubuntu.
> 
> Thank you, I will try to make a Ubuntu .img on my starfive visionfive v1

How is this img made, is there a related blog?
