### ISSUE TITLE
50 MHz SDIO bus not working for some SD cards

### ISSUE THREAD

**Issue by pdp7** [starfive-tech/Fedora_on_StarFive#23]
@tommythorn reports:
> reading from NFS vs SDcard:
> 
> NFS: 22.8 MB/s (the same on my dev box gets 170 MB/s via 10 GbE)
> SDCard: 4.6 MB/s (and it's a highend card which will get > 50 MB/s normally).
> So, for now and with production hardware, NFS > SDcard. I haven’t tried USB.
>
> FWIW I tested both using `dd bs=8192 status=progress`, 
> e.g. `sudo dd status=progress bs=8192 if=/dev/mmcblk1 of=/dev/null`

@tekkamanninja @MichaelZhuxx: The [Seeed FAQ shows 22 MB/s with SD card](https://wiki.seeedstudio.com/BeagleV-Getting-Started/#faq).  I presume this means it was Linux 4.19 that Seeed tested with?  Maybe there is a problem with 5.10 on the Fedora image that is causing it to be 4.6 MB/s?

**Comment by robertlipe** [comment]
Is it possible this is a manifestation of https://github.com/starfive-tech/beaglev_fedora/issues/20 ?

**Comment by tommythorn** [comment]
I see no traffic in dmesg so I don’t think so

**Comment by tgeek77** [comment]
I'm getting the same performance. I tested the microsd card on another machine and for 25-30 MB/s but on the BeagleV, I am getting the same performance as @tommythorn.

**Comment by MichaelZhuxx** [comment]
after update the frequency in dts as below:
```
--- a/arch/riscv/dts/starfive_vic7100_beagle_v.dts
+++ b/arch/riscv/dts/starfive_vic7100_beagle_v.dts
@@ -556,7 +556,7 @@
                        clocks = <&dwmmc_biuclk>;
                        clock-names = "biu";
                        clock-frequency = <100000000>;
-                       max-frequency = <10000000>;
+                       max-frequency = <50000000>;
                        fifo-depth = <32>;
                        card-detect-delay = <300>;
                        fifo-watermark-aligned;
```
the system will pop up the below message

```
[  911.725040] audit: type=1130 audit(1607040900.747:798): pid=1 uid=0 auid=4294967295 ses=429496729'
[  911.816845] audit: type=1131 audit(1607040900.747:799): pid=1 uid=0 auid=4294967295 ses=429496729'
[  920.872770] audit: type=1131 audit(1607040909.887:800): pid=1 uid=0 auid=4294967295 ses=429496729'
[  921.126239] audit: type=1130 audit(1607040910.147:801): pid=1 uid=0 auid=4294967295 ses=429496729'
[  921.177968] audit: type=1131 audit(1607040910.147:802): pid=1 uid=0 auid=4294967295 ses=429496729'
[  921.230732] audit: type=1130 audit(1607040910.237:803): pid=1 uid=0 auid=4294967295 ses=429496729'
[  921.281850] audit: type=1701 audit(1607040910.297:804): auid=4294967295 uid=0 gid=0 ses=4294967291
[  921.404099] audit: type=1334 audit(1607040910.417:805): prog-id=149 op=LOAD
[  921.444058] audit: type=1334 audit(1607040910.417:806): prog-id=150 op=LOAD
[  921.484401] audit: type=1334 audit(1607040910.417:807): prog-id=151 op=LOAD
[  921.524043] audit: type=1325 audit(1607040910.437:808): table=filter family=7 entries=0 op=xt_reg"
[  921.568324] audit: type=1325 audit(1607040910.437:808): table=broute family=7 entries=0 op=xt_reg"
[  946.284639] kauditd_printk_skb: 9 callbacks suppressed
```

**Comment by pdp7** [comment]
@tekkamanninja @esmil @geertu interesting results from @MichaelZhuxx when changing the frequency

**Comment by MichaelZhuxx** [comment]
sorry for missing test data 
```
[root@fedora-starfive ~]# time dd if=/dev/mmcblk1p2 of=/dev/null bs=512k count=5000
5000+0 records in
5000+0 records out
2621440000 bytes (2.6 GB, 2.4 GiB) copied, 110.666 s, 23.7 MB/s

real    1m50.673s
user    0m0.033s
sys     0m15.706s
```

**Comment by esmil** [comment]
That's great. I see similar numbers after raising the max frequency to 50MHz.

**Comment by esmil** [comment]
While it seems to work for both me and @mcd500, @teknoraver has issues with raising the max frequency to 50MHz:
https://pastebin.com/vTHDjrKF

**Comment by kraj** [comment]
on yocto with 5.13-rc3

```
root@beaglev-starlight-jh7100:~# dd if=/dev/urandom of=rnd_data bs=512k count=1000
1000+0 records in
1000+0 records out
524288000 bytes (524 MB, 500 MiB) copied, 23.6062 s, 22.2 MB/s
```

**Comment by tommythorn** [comment]
Confirm that I also now get 22+ MB/s with Akira-san's image ( Fedora-riscv64-vic7100-xfce-dev-Rawhide-20210516233526.n.0-sda-akira-5.13.rc3.raw.zst)

**Comment by pdp7** [comment]
@MichaelZhuxx @tekkamanninja it appears @teknoraver had trouble when increasing the frequency so maybe there is variance between different boards?  https://github.com/starfive-tech/Fedora_on_StarFive/issues/23#issuecomment-847386417

@esmil is that why you are keeping that frequency change out of https://github.com/starfive-tech/linux/tree/esmil_starlight ?

**Comment by teknoraver** [comment]
Yes, that change broke sdcard for me. It boots, and then the card start making errors until it seems removed:
```
[   26.648179] mmc0: card 1234 removed
[   26.735655] mmc_host mmc0: Bus speed (slot 0) = 100000000Hz (slot req 400000Hz, actual 400000HZ div = 125)
[   26.794686] mmc_host mmc0: Bus speed (slot 0) = 100000000Hz (slot req 50000000Hz, actual 50000000HZ div = 1)
[   26.804597] mmc0: error -84 whilst initialising SD card
[   26.823688] mmc_host mmc0: Bus speed (slot 0) = 100000000Hz (slot req 300000Hz, actual 299401HZ div = 167)
[   26.887392] mmc_host mmc0: Bus speed (slot 0) = 100000000Hz (slot req 50000000Hz, actual 50000000HZ div = 1)
[   26.897305] mmc0: error -84 whilst initialising SD card
[   26.916359] mmc_host mmc0: Bus speed (slot 0) = 100000000Hz (slot req 200000Hz, actual 200000HZ div = 250)
[   26.989895] mmc_host mmc0: Bus speed (slot 0) = 100000000Hz (slot req 50000000Hz, actual 50000000HZ div = 1)
[   26.999785] mmc0: new high speed SDHC card at address 1234
[   27.007687] mmcblk0: mmc0:1234 SA16G 14.4 GiB 
[   27.017953]  mmcblk0: p1 p2 p3
[   27.021757] debugfs: Directory 'mmcblk0' with parent 'block' already present!
[   28.728211] mmc0: card 1234 removed
```

**Comment by esmil** [comment]
@pdp7 Yes, that's exactly why. After you found the missing `broken-cd;` property broke sdcard detection for you others have also run into it, so when @teknoraver found it didn't work for him I didn't want to break the starlight branch for others too.

It'd be cool if we could somehow figure out it's just @teknoraver's board/card. I guess one way to do that would be to just re-apply the change and wait for more people to complain, but hopefully we can find a nicer solution.

**Comment by MichaelZhuxx** [comment]
Beta developers who are having problems with SD card read/write, here is a suggestion that please add c_macro "_SET_SYSCON_REG_register50_SCFG_sdio0_cclk_dlychain_sel(v)" in [INIT_FUNC_DEF(sdio0)](https://github.com/starfive-tech/u-boot/blob/93099a61c7b048ba1926152629284f8810cb6940/board/starfive/vic7100/vic7100.c#L509) to adjust delay shift between clk and data signal. the value of v is 0~31 which means the delay_shift(sel) = 0.16 * sel (ns). please have a try and sort out a appropriate value. thanks

![image](https://user-images.githubusercontent.com/78013124/120622214-30070300-c491-11eb-90b3-3a7b340f3abe.png)

**Comment by pdp7** [comment]
@teknoraver could you please try the fw_payload.bin.out that @mcd500 has linked in this post?
https://forum.beagleboard.org/t/new-firmware-boot-hang-is-fixed/29986/3

We think it may improve the problems that some people have been having with SD card stability

**Comment by teknoraver** [comment]
I can, but I didn't have stability with the SD card, except with the high frequency patch

**Comment by teknoraver** [comment]
ANyway, with the new fw and the patch, I still get this:
```
[   61.209784] mmc0: card 1234 removed
[   61.355262] mmc0: new high speed SDHC card at address 1234
[   61.363387] mmcblk0: mmc0:1234 SA16G 14.4 GiB 
[   62.060444]  mmcblk0: p1 p2 p3
[   62.064197] debugfs: Directory 'mmcblk0' with parent 'block' already present!
[   63.769728] mmc0: card 1234 removed
[   63.865560] mmc0: new high speed SDHC card at address 1234
[   63.877439] mmcblk0: mmc0:1234 SA16G 14.4 GiB 
[   64.549542] F2FS-fs (mmcblk0p2): Issue discard(479060, 479060, 1) failed, ret: -5
[   64.549567] F2FS-fs (mmcblk0p2): Issue discard(479064, 479064, 1) failed, ret: -5
[   64.580425]  mmcblk0: p1 p2 p3
[   64.591660] debugfs: Directory 'mmcblk0' with parent 'block' already present!
[   65.609730] mmc0: card 1234 removed
[   65.712979] mmc0: new high speed SDHC card at address 1234
[   65.721099] mmcblk0: mmc0:1234 SA16G 14.4 GiB 
[   66.420438]  mmcblk0: p1 p2 p3
[   66.424161] debugfs: Directory 'mmcblk0' with parent 'block' already present!
[   67.449692] mmc0: card 1234 removed
[   67.562955] mmc0: new high speed SDHC card at address 1234
[   67.571207] mmcblk0: mmc0:1234 SA16G 14.4 GiB 
[   68.270393]  mmcblk0: p1 p2 p3
[   68.274075] debugfs: Directory 'mmcblk0' with parent 'block' already present!
[   69.289689] mmc0: card 1234 removed
[   69.392869] mmc0: new high speed SDHC card at address 1234
[   69.400307] mmcblk0: mmc0:1234 SA16G 14.4 GiB 
[   70.100390]  mmcblk0: p1 p2 p3
[   70.104064] debugfs: Directory 'mmcblk0' with parent 'block' already present!
```

**Comment by esmil** [comment]
@matteo Which patch is that exactly. That looks like mmc0  is probed twice..

**Comment by teknoraver** [comment]
@esmil well, when I get stability issues the card seems being inserted and removed continuously, even it it's always inserted,
so I see those probe messages

**Comment by pdp7** [comment]
@MichaelZhuxx any suggestions given what Matteo Croce (@teknoraver) is [seeing in that log](https://github.com/starfive-tech/Fedora_on_StarFive/issues/23#issuecomment-859736191)?

**Comment by pdp7** [comment]
@teknoraver do you still seem performance issues with the newer SD cards that you have?  I am trying to determine if there is anyone for which 50 MHz does not.

**Comment by mcd500** [comment]
I finally had a time to investigate the sd card.
Without 50Mhz patch, it works, just not at the optimal speed.
With the 50Mhz patch, good speed but found two sd cards fail to boot. 

The log for working SD
```
[root@fedora-starfive ~]# dmesg | grep mmc1
[    2.750257] mmc_host mmc1: card is non-removable.
[    2.827147] mmc_host mmc1: Bus speed (slot 0) = 100000000Hz (slot req 400000Hz, actual)
[    2.926297] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    3.033383] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    3.280961] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    3.379680] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    3.446292] mmc1: queuing unknown CIS tuple 0x81 (9 bytes)
[    3.572092] mmc_host mmc1: Bus speed (slot 0) = 100000000Hz (slot req 10000000Hz, actu)
[    3.611552] mmc1: new high speed SDIO card at address 0001
[root@fedora-starfive ~]# dmesg | grep mmc0
[    2.591564] mmc_host mmc0: card is polling.
[    2.663562] mmc_host mmc0: Bus speed (slot 0) = 100000000Hz (slot req 400000Hz, actual)
[    4.009235] mmc_host mmc0: Bus speed (slot 0) = 100000000Hz (slot req 50000000Hz, actu)
[    4.080417] mmc0: new high speed SDHC card at address 0001
[    4.114898] mmcblk0: mmc0:0001 00000 14.9 GiB
```

The log for not working SD
```
mmc_host mmc0: card is polling.
mmc_host mmc1: card is non-removable.
mmc_host mmc0: Bus speed (slot 0) = 100000000Hz (slot req 400000Hz, actual 400000HZ div =)
mmc_host mmc1: Bus speed (slot 0) = 100000000Hz (slot req 400000Hz, actual 400000HZ div =)
mmc_host mmc0: Bus speed (slot 0) = 100000000Hz (slot req 50000000Hz, actual 50000000HZ d)
mmc0: new high speed SDHC card at address b368
mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
mmcblk0: mmc0:b368       7.46 GiB
mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
systemd[1]: Detected architecture riscv64.
 mmcblk0: p1 p2
mmc_host mmc1: Bus speed (slot 0) = 100000000Hz (slot req 10000000Hz, actual 10000000HZ d)
mmc1: new high speed SDHC card at address 0001
```

The line in not working SD is suspicious.
```
mmc0: new high speed SDHC card at address b368
```

I will look into it deeper.

**Comment by teknoraver** [comment]
Indeed, some cards are failing.
Can you try with 25 Mhz? That worked for all cards for me

**Comment by mcd500** [comment]
I will try 25MHz. The most difficulty was to find the sd cards which fails, only two out of all others I have.

**Comment by pdp7** [comment]
@teknoraver @mcd500 any updates?  We still have some cards that can not hit 50MHz right?

**Comment by teknoraver** [comment]
Yes, at least two models

**Comment by pdp7** [comment]
> I finally had a time to investigate the sd card.
> Without 50Mhz patch, it works, just not at the optimal speed.
> With the 50Mhz patch, good speed but found two sd cards fail to boot.

@mcd500 what manufacturer and model are those SD cards?

@MichaelZhuxx would like to try to reproduce does not have a SD card that fails at 50 MHz

**Comment by teknoraver** [comment]
> @mcd500 what manufacturer and model are those SD cards?

For me, a Kingston 16 GB card, labeled SA16G

**Comment by MichaelZhuxx** [comment]
> > @mcd500 what manufacturer and model are those SD cards?
> 
> For me, a Kingston 16 GB card, labeled SA16G

could you please take a picture for this TF card, I can buy the same one for testing

**Comment by teknoraver** [comment]
We were collecting picture of the cards, but I don't remember where.
@pdp7 do you have the URL?

**Comment by MichaelZhuxx** [comment]
> We were collecting picture of the cards, but I don't remember where.
> @pdp7 do you have the URL?

do you mean this link?https://forum.beagleboard.org/t/known-good-sd-cards/29958

**Comment by teknoraver** [comment]
Yes, that's my card:

https://forum.beagleboard.org/uploads/default/original/2X/f/f8e0154b11fe6546d863902e5c4025b00f7cbabc.jpeg

**Comment by MichaelZhuxx** [comment]
> Yes, that's my card:
> 
> https://forum.beagleboard.org/uploads/default/original/2X/f/f8e0154b11fe6546d863902e5c4025b00f7cbabc.jpeg

This TF card is no longer available in the market. we have verified three type of TF card and no issue happened.

![image](https://user-images.githubusercontent.com/78013124/126185428-11b00fb7-c3cb-4e8a-aa16-5666c453aea3.png)

**Comment by MichaelZhuxx** [comment]
Update the progress:
I got several type of TF card, these cards are working well, such as SanDisk, Lexar, SUMSUNG
![image](https://user-images.githubusercontent.com/78013124/126578866-8ccf2f9f-7230-44a6-889c-294774f917bf.png)

but unfortunately, below cards(I guess it's only avaliable on China market) has a problem on booting, I need do a deep dive on that
![image](https://user-images.githubusercontent.com/78013124/126579080-4c7d8465-82ff-4815-8803-b3146bdd898f.png)

**Comment by MichaelZhuxx** [comment]
Update:

I add "_SET_SYSCON_REG_register50_SCFG_sdio0_cclk_dlychain_sel(**12**)" in [INIT_FUNC_DEF(sdio0)](https://github.com/starfive-tech/u-boot/blob/93099a61c7b048ba1926152629284f8810cb6940/board/starfive/vic7100/vic7100.c#L509) for u-boot and run it with 50MHz patch. All above cards(SanDisk, SUMSUNG, TOSHIBA, KINGSTON, Lexar, aigo, etc.) are working well.

@teknoraver please download the u-boot and dtb [binary](https://drive.google.com/drive/folders/1Q-52T96bvIbws_C2IKhNa72StDxSi_fX?usp=sharing) and try it. looking forward to hearing from your test result.

> Beta developers who are having problems with SD card read/write, here is a suggestion that please add c_macro "_SET_SYSCON_REG_register50_SCFG_sdio0_cclk_dlychain_sel(v)" in [INIT_FUNC_DEF(sdio0)](https://github.com/starfive-tech/u-boot/blob/93099a61c7b048ba1926152629284f8810cb6940/board/starfive/vic7100/vic7100.c#L509) to adjust delay shift between clk and data signal. the value of v is 0~31 which means the delay_shift(sel) = 0.16 * sel (ns). please have a try and sort out a appropriate value. thanks @mcd500, @teknoraver @pdp7
> 
> ![image](https://user-images.githubusercontent.com/78013124/120622214-30070300-c491-11eb-90b3-3a7b340f3abe.png)

**Comment by MichaelZhuxx** [comment]
Verified in new Fedora Image [Fedora-riscv64-developer-xfce-with-esp-Rawhide-20210822.n.0-sda.raw.zst](https://fedora.starfivetech.com/pub/downloads/BeagleV-release/Fedora-riscv64-developer-xfce-with-esp-Rawhide-20210822.n.0-sda.raw.zst), and test result is as below shown:

**Comment by tgeek77** [comment]
> Verified in new Fedora Image [Fedora-riscv64-developer-xfce-with-esp-Rawhide-20210822.n.0-sda.raw.zst](https://fedora.starfivetech.com/pub/downloads/BeagleV-release/Fedora-riscv64-developer-xfce-with-esp-Rawhide-20210822.n.0-sda.raw.zst), and test result is as below shown:

That URL doesn't work.

**Comment by esmil** [comment]
It seems the day was bumped. See https://fedora.starfivetech.com/pub/downloads/BeagleV-release/

**Comment by MichaelZhuxx** [comment]
@esmil @tgeek77 sorry for the inconvenience, the link is ok now
