### ISSUE TITLE
Missing "boot2" definition trying to boot Fedora on the board

### ISSUE THREAD

**Issue by sxa** [starfive-tech/Fedora_on_StarFive#24]
I'm trying to boot the board but it doesn't seem to be getting as far as reading the SD card. If I use `mmcinfo` it can see it, but the boot sequence, when viewed over the serial console gives this:
```
Hit any key to stop autoboot:  0 
## Unknown partition table type 0
** No partition table - mmc 0 **
## Warning: Input data exceeds 1048576 bytes - truncated
## Info: input data size = 1048578 = 0x100002
## Error: Environment import failed: errno = 12
running boot2...
## Error: "boot2" not defined
```
It looks like the default `bootcmd` definition is `run mmcsetup; run fdtsetup; run fatenv; echo 'running boot2...'; run boot2` but there is no `boot2` definition in the environment and I'm not clear. Does this need to be explicitly set and do others' boards have something already in that field and can share it?
(I haven't touched the parameters since I took the board out of the box, as up until today I didn't have a serial console cable to be able to even look at the definitions)

**Comment by pdp7** [comment]
@tekkamanninja any suggestions?

**Comment by pcotret** [comment]
Well, it seems your SD card doesn't have a partition table. I got a similar error: I had to write a partition table (for instance, with GParted) before flashing my SD card.

**Comment by sxa** [comment]
> Well, it seems your SD card doesn't have a partition table. I got a similar error: I had to write a partition table (for instance, with GParted) before flashing my SD card.

@pcotret I'm not sure I follow - the SD card image has a partition table inside it so when you write the SD card direct to the `/dev/mmcblk0` (or whatever's appropriate) it gets the partition table from that:
```
Disk /dev/mmcblk0: 15.9 GB, 15931539456 bytes, 31116288 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: dos
Disk identifier: 0x12345678

        Device Boot      Start         End      Blocks   Id  System
/dev/mmcblk0p1   *        8192      409599      200704   83  Linux
/dev/mmcblk0p2          409600    31116287    15353344   83  Linux
```
I'm not sure how putting anything on beforehand with gparted would help, since it'll get overwritten wh you `dd` over the whole device.

**Comment by sxa** [comment]
Good news: Reflashing with the firmware from built from the instructions in https://bootlin.com/blog/buildroot-beagle-v/ has resolved my problem and allowed the board to boot properly with the Fedora image :-)
