### ISSUE TITLE
ethernet: no broadcast from linux?

### ISSUE THREAD

**Issue by rminnich** [starfive-tech/Fedora_on_StarFive#28]
I'm seeing a problem with the ethernet that I put down to Linux driver
problem. It's pretty simple: the kernel seems unable to send a
broadcast packet, which makes kernel-level and program-level dhcp
client and ARP support hard.

dhcp in u-boot works fine. ping in u-boot works fine and populates ARP caches.

What I can't do is run dhcp client in user mode, and it seems to
always get back to inability to send a broadcast packet.

I also see that the network, when pushed hard, seems to hang; I also
put this down to a possible Linux driver issue, but I'm not sure.

**Comment by pdp7** [comment]
@MichaelZhuxx @tekkamanninja have either of you encountered issue like this?

**Comment by pdp7** [comment]
@rminnich are you still having this issue?  if so, could show the commands you using so we can reproduce?

**Comment by pdp7** [comment]
@rminnich is this still problem?

**Comment by pdp7** [comment]
@rminnich ok to close this?

**Comment by pdp7** [comment]
please reopen if still a problem
