### ISSUE TITLE
[kernel] IPv6 not working on Ethernet interface

### ISSUE THREAD

**Issue by aurel32** [starfive-tech/Fedora_on_StarFive#29]
IPv6 is partially functional on the BeagleV board. It appears that the eth0 interface doesn't answer to IPv6 ICMP neighbor solicitation, so connections to the board can't be make in IPv6. I guess multicast doesn't properly work in the Ethernet driver.

A workaround is to set the eth0 interface to promiscuous.

**Comment by aurel32** [comment]
Note that this is fixed by the work from @atishp04 fixing the non-coherent dma issue.

**Comment by pdp7** [comment]
@aurel32 great to hear!  What branch did you use to test with?

**Comment by pdp7** [comment]
Fixed with this branch https://github.com/esmil/linux/tree/starlight-nc
