### ISSUE TITLE
[Documentation] HDMI display list

### ISSUE THREAD

**Issue by pdp7** [starfive-tech/Fedora_on_StarFive#32]
list of monitors that are know to work and monitor that are known not to work are here:

**HDMI displays compatible list** 
https://forum.beagleboard.org/t/hdmi-displays-compatible-list/29665

if you can not access, then email drew@beagleboard.org

**Comment by pdp7** [comment]
From the forum:
https://forum.beagleboard.org/t/hdmi-displays-compatible-list/29665/28
> If you want to play with other resolutions, it appears that the clock configuration in starfive_fb.c has only been written for 800x600 and 1920x1080. The 1920x1080 mode seems to specify a /24 divider, and if we believe it is 78.5 MHz, then 800x600 with its /54 divider is 34.89 MHz? If so that would again be non-standard. There are placeholders for 640x480 and 1280x720 but they just print a warning saying that they are incomplete. I tried to look on-line for a definition of the CLK_LCDC_OCLK_CTRL register in the Frame Buffer peripheral (which is where these values end up), but got nothing.

@MichaelZhuxx any idea how to improve compatibility?

**Comment by MichaelZhuxx** [comment]
The [lastest kernel](https://github.com/starfive-tech/linux/tree/starlight) has support DRM framework for display, it also fixed the "out of range" and "Not support/Blank" issue for some monitors. please have a try and let me know if it's still a problem.

**Comment by archanox** [comment]
> The [lastest kernel](https://github.com/starfive-tech/linux/tree/starlight) has support DRM framework for display, it also fixed the "out of range" and "Not support/Blank" issue for some monitors. please have a try and let me know if it's still a problem.

Thanks @MichaelZhuxx I've flashed my BeagleV successfully and tested it against my "lapdock" found here 

> AU $443.72  45％ Off | EVICIV Raspberry Pi 4 3 Laptop Raspbook Touchscreen Keyboard Battery RasPi Rechargeable Portable Monitor RPi LCD Display Lapdock
https://a.aliexpress.com/_mM8Rrwi

There are some blemishes to the image quality, but it's completely usable with an external display. This could be attributed to the software rendering.
