### ISSUE TITLE
grant pdp7 (Drew) permissions to merge PR's

### ISSUE THREAD

**Issue by pdp7** [starfive-tech/Fedora_on_StarFive#36]
grant my account https://github.com/pdp7 permissions to merge Pull Requests in this repo so I can easily update the README

**Comment by pdp7** [comment]
@tekkamanninja @MichaelZhuxx do you have permissions to do this?

**Comment by MichaelZhuxx** [comment]
Done. @pdp7 please try it

**Comment by pdp7** [comment]
@MichaelZhuxx it does not look like I have write access 
![Screenshot from 2021-05-17 23-37-18](https://user-images.githubusercontent.com/313864/118603533-df8d6700-b768-11eb-95cd-83bbf907eb9c.png)

**Comment by pdp7** [comment]
@MichaelZhuxx sorry, I had to click Accept on your invite.  It now works ok.  Thank you.
