### ISSUE TITLE
[Bluetooth] Cannot be loaded normally

### ISSUE THREAD

**Issue by MichaelZhuxx** [starfive-tech/Fedora_on_StarFive#4]
Based on fedora image: Fedora-riscv64-vic7100-dev-raw-image-Rawhide-20210419121453.n.0-sda.raw

Input the following command in fedora shell, 

```
[root@fedora-starfive /]# hciconfig hci0 up
[  880.671327] Bluetooth: Core ver 2.22
[  880.703333] NET: Registered protocol family 31
[  880.736030] Bluetooth: HCI device and connection manager initialized
[  880.770890] Bluetooth: HCI socket layer initialized
[  880.804406] Bluetooth: L2CAP socket layer initialized
[  880.837969] Bluetooth: SCO socket layer initialized
Can't get device info: No such device
```

**Comment by pdp7** [comment]
Please try this again once the Fedora image has 5.13 kernel brcmfmac driver

**Comment by pdp7** [comment]
FYI - I have tested and confirmed that this patch "drivers/tty/serial/8250: update driver for VIC7100" is not needed for the console (uart3) to function correctly.  We are taking it out of the 5.13 kernel as this change is not done in a way that can be upstreamed:
https://github.com/esmil/linux/pull/21

My goal is to get support into upstream Linux kernel for a minimum booting BeagleV Starlight JH7100 board.

At some point I imagine we will try to get Bluetooth working with the upstream kernel.  I wanted to make note of https://github.com/starfive-tech/linux/commit/26d688fb4ff7150ab21eaeda2d6cd14ca86a2171 as we may need to figure out how to achieve that same functional change in the correct way.  It still remains unclear exactly why the hs_uart (uart0 and uart1) need this change.  Is it just performance?  Or did it not functional at all without it?  These are questions that can be investigated in the future

cc @davidlt

**Comment by esmil** [comment]
@pdp re bluetooth. The last two commits here is what I've tried, but it doesn't quite work yet: https://github.com/esmil/linux/commits/starlight-bt

**Comment by pdp7** [comment]
@esmil do you think we are ok without the ifdef hack in https://github.com/starfive-tech/linux/commit/26d688fb4ff7150ab21eaeda2d6cd14ca86a2171 ?

**Comment by esmil** [comment]
@pdp7 Yeah, as I said on slack, to me it just looks like an optimization to make use of the full fifo. I'll just drop it when I rebase on rc6.

btw. "net: stmmac: Configure gtxclk based on speed" is another patch where ethernet seems to work fine without, but maybe not as efficient

**Comment by pdp7** [comment]
@esmil any idea what we should try next?  BT is still not working I think?

**Comment by esmil** [comment]
@pdp7 I think a good next step would be to try those two commits and then look at the serial communication with a scope or other probe to see if it actually manages to send anything to the bluetooth module. It might be that pinmux/pinconf is not set up properly and the signal doesn't even make it out or maybe a clock is not setup properly and the bitrate is wrong.

**Comment by MichaelZhuxx** [comment]
This issue has been fixed on latest[linux kernel](https://github.com/starfive-tech/linux/tree/starlight)
