### ISSUE TITLE
[WIFI] BCMDHD cannot be loaded sometimes

### ISSUE THREAD

**Issue by MichaelZhuxx** [starfive-tech/Fedora_on_StarFive#6]
Based on fedora image: Fedora-riscv64-vic7100-dev-raw-image-Rawhide-20210419121453.n.0-sda.raw

After system starts, we need modprobe the wifi driver manually for this image as below 

`[root@fedora-starfive ~]# modprobe bcmdhd`

sometimes bcmdhd cannot be loaded successfully as below snapshot

![微信图片_20210421194226](https://user-images.githubusercontent.com/78013124/115548153-b8628780-a2d9-11eb-96c5-aa5e0d35efdf.png)

**Comment by cybergaszcz** [comment]
In my observations I see that after system start the module usually loads fine but the following problem occurs also when I manually unload and load again this module:
`[riscv@fedora-starfive ~]$ sudo modprobe -v bcmdhd 
insmod /lib/modules/5.10.6+/kernel/net/wireless/cfg80211.ko.xz 
[  363.692216] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[  363.728652] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
insmod /lib/modules/5.10.6+/kernel/drivers/net/wireless/broadcom/bcmdhd/bcmdhd.ko.xz 
[  392.156398] watchdog: BUG: soft lockup - CPU#1 stuck for 23s! [modprobe:660]
[  392.189934] Modules linked in: cfg80211 nft_fib_inet nft_fib_ipv4 nft_fib_ipv6 nft_fib nft_reject_inet nf_reject_ipv4 nf_reject_ipv6 nft_reject nft_ct nft_chain_nat nf_tables ebtable_nat ebtable_broute ip6ta]
[  392.315578] CPU: 1 PID: 660 Comm: modprobe Tainted: G        W    L    5.10.6+ #26
[  392.351044] epc: ffffffe0002054a0 ra : ffffffe0002053fc sp : ffffffe084403bf0
[  392.386010]  gp : ffffffe0018416a8 tp : ffffffe0828a9ac0 t0 : 0000000000003614
[  392.421074]  t1 : ffffffdf81ebb3d0 t2 : 000000000001e294 s0 : ffffffe084403c80
[  392.456021]  s1 : ffffffd0043d1e80 a0 : 0000000000003614 a1 : ffffffdf81e30000
[  392.490962]  a2 : ffffffdf81ebb3cc a3 : 0000000000010c05 a4 : ffffffdf81e54d68
[  392.525906]  a5 : ffffffd00425f150 a6 : 000000000000e1f4 a7 : 0000000000000000
[  392.560770]  s2 : ffffffd0043d1300 s3 : ffffffdf81f1c980 s4 : 0000000000000017
[  392.595673]  s5 : fffffffffffff000 s6 : 0000000000000014 s7 : ffffffd00420df70
[  392.630716]  s8 : ffffffd0043d1400 s9 : 000000000000e1f4 s10: 0000000000003614
[  392.665660]  s11: ffffffdf81ebb3cc t3 : 0000000000000100 t4 : ffffffe000204f38
[  392.700790]  t5 : 0000000000192078 t6 : ffffffdf82d201e0
[  392.734094] status: 0000000200000120 badaddr: 0000000000000000 cause: 8000000000000005
[  402.809058] [dhd] dhd_module_init: in Dongle Host Driver, version 100.10.545.13 (r826445-20200914-2)
[  402.846759] [dhd] ======== dhd_wlan_init_plat_data ========
[  402.881314] [dhd] dhd_wlan_init_gpio: WL_REG_ON=37
[  402.914566] [dhd] dhd_wifi_platform_load: Enter
[  402.947520] [dhd] Power-up adapter 'DHD generic adapter'
[  402.982709] dummy_sdmmc: probe of mmc0:0001:1 failed with error -110
[  403.019139] dummy_sdmmc: probe of mmc0:0001:2 failed with error -110
[  403.054844] [dhd] wifi_platform_set_power = 1, delay: 200 msec
[  403.089463] [dhd] ======== PULL WL_REG_ON(37) HIGH! ========
[  403.436594] [dhd] wifi_platform_bus_enumerate device present 1
[  403.470730] [dhd] ======== Card detection to detect SDIO card! ========
[  403.505634] mmc0:mmc host rescan start!
[  405.606480] [dhd] failed to power up DHD generic adapter, 0 retry left
[  405.657563] [dhd] wifi_platform_set_power = 0, delay: 0 msec
[  405.691511] [dhd] ======== PULL WL_REG_ON(37) LOW! ========
[  405.725409] [dhd] wifi_platform_bus_enumerate device present 0
[  405.759552] [dhd] ======== Card detection to remove SDIO card! ========
[  405.794480] mmc0:mmc host rescan start!
[  405.826604] [dhd] failed to power up DHD generic adapter, max retry reached**
[  405.862284] [dhd] unregister wifi platform drivers
[  405.895457] [dhd] wifi_platform_bus_enumerate device present 0
[  405.929747] [dhd] ======== Card detection to remove SDIO card! ========
[  405.964832] mmc0:mmc host rescan start!
[  405.997096] [dhd] ======== dhd_wlan_deinit_plat_data ========
[  406.031286] [dhd] dhd_wlan_deinit_gpio: gpio_free(WL_REG_ON 37)
[  406.066008] [dhd] dhd_module_init: Failed to load the driver, try cnt 0
[  406.101370] [dhd] dhd_module_init: Failed to load driver max retry reached**
[  406.136878] [dhd] dhd_module_init: Exit err=-19
modprobe: ERROR: could not insert 'bcmdhd': No such device
`

**Comment by pdp7** [comment]
FYI - we may want to move to brcmfmac driver instead of bcmdhd.  @robertcnelson has the device tree snippet needed https://github.com/RobertCNelson/linux-stable-rcn-ee/blob/679febbc6b60f06ae80ba0edc8e0bfe192dfc312/arch/riscv/boot/dts/starfive/jh7100-starlight.dts#L141-L156  @sarnold has more information

**Comment by pdp7** [comment]
We are no longer using bcmdhd.

New Fedora image (July 7th) from @tekkamanninja: 
https://beagleboard.org/~pdp7/Fedora-riscv64-vic7100-xfce-dev-Rawhide-20210707.n.0-sda.raw.zst 

sha256sum: 239f439125afce187c34b530490e6e3d095bf98ee6ef03b6d212842f1a4dba32 

https://forum.beagleboard.org/t/new-fedora-image-july-7th/30217
